# Tarea 1 NLP : Competencia de Clasificación de Texto
-------------------------------


- **Nombres:** Valentina Sepulveda, Joaquín Pérez

- **Usuario o nombre de equipo en Codalab:** 




### Detalles e instrucciones de la competencia:

- La competencia consiste en resolver 4 problemas de clasificación distintos, cada uno de tres clases. Por cada problema deberán crear un clasificador distinto. La evaluación de la competencia se realiza en base a 4 métricas: AUC, Kappa y Accuracy. Los mejores puntajes en cada ítem serán los que ganen.

- Para comenzar se les entregará en este notebook el baseline y la estructura del reporte. El baseline es el código que realiza creación de features y clasificación básica. Los puntajes de este serán ocupados como base para la competencia: deben superar sus resultados para ser bien evaluados.  

- Para participar, deben registrarse en Codalab y luego ingresar a la competencia usando el siguiente [link]( https://competitions.codalab.org/competitions/24121?secret_key=f5eb2d95-b36e-4aad-8fc5-4d9d77f4e4dc). 

- **Es requisito entregar el reporte con el código y haber participado en la competencia para ser evaluado.**

- Pueden hacer grupos de máximo 2 alumnos. Cada grupo debe tener un nombre de equipo (En codalab, ir a settings y después cambiar Team Name). Solo una persona debe administrar la cuenta del grupo.

- En total pueden hacer un **máximo de 4 envíos/submissions** (tanto para equipos como para envíos indivuales).

- Hagan varios experimentos haciendo cross-validation o evaluación sobre una sub-partición antes de enviar sus predicciones a Codalab. Asegúrense que la distribución de las clases sea balanceada en las particiones de training y testing. Verificar que el formato de la submission coincida con el de la competencia. De lo contrario, se les será evaluado incorrectamente.

- Estar top 5 en alguna métrica equivale a 1 punto extra en la nota final.

- No se limiten a los contenidos vistos ni a scikit ni a este baseline. ¡Usen todo su conocimiento e ingenio en mejorar sus sistemas! 

- Todas las dudas escríbanlas en el hilo de U-cursos de la tarea. Los emails que lleguen al equipo docente serán remitidos a ese medio.


### Reporte

Este debe cumplir la siguiente estructura:

1.	**Introducción**: Presentar brevemente el problema a resolver, los métodos y representaciones utilizadas en el desarrollo de la tarea y conclusiones obtenidas. (0.5 Puntos)
2.	**Representaciones**: Describir los atributos y representaciones usadas como entrada de los clasificadores. Si bien, con Bag of Words (baseline) ya se comienzan a percibir buenos resultados, pueden mejorar su evaluación agregando más atributos y representaciones diseñadas a mano. Mas abajo encontrarán una lista útil de estos que les podrá ser de utilidad. (1.5 puntos)
3.	**Algoritmos**: Describir brevemente los algoritmos de clasificación usados. (0.5 puntos)
4.	**Métricas de evaluación**: Describir brevemente las métricas utilizadas en la evaluación indicando que miden y su interpretación. (0.5 puntos)
5.	**Experimentos**: Reportar todos sus experimentos. Comparar los resultados obtenidos utilizando diferentes algoritmos y representaciones. Estos experimentos los hacen sobre la sub-partición de evaluación que deben crear (o pueden usar cross-validation). Incluyan todo el código de sus experimentos aquí. ¡Es vital haber realizado varios experimentos para sacar una buena nota! (2 puntos)
6.	**Conclusiones**: Discutir resultados, proponer trabajo futuro. (1 punto)

### Baseline

Por último, el baseline contiene un código básico que:

- Obtiene los dataset.
- Divide los datasets en train (entrenamiento y prueba) y target set (el que clasificar para subir a la competencia).
- Crea un Pipeline que: 
    - Crea features personalizadas.
    - Transforma los dataset a bag of words (BoW).  
    - Entrena un clasificador usando cada train set.
- Clasifica y evalua el sistema creado usando el test set.
- Clasifica el target set.
- Genera una submission con el target en formato zip en el directorio en donde se está ejecutando el notebook. 


Algunas pistas sobre como mejorar el rendimiento de los sistemas que creen. (Esto tendrá mas sentido cuando vean el código)

- **Vectorizador**: investigar los modulos de `nltk`, en particular, `TweetTokenizer`, `mark_negation` para reemplazar los tokenizadores. También, el parámetro `ngram_range` (Ojo que el clf naive bayes no debería usarse con n-gramas, ya que rompe el supuesto de independencia). Además, implementar los atributos que crean útiles desde el listado del el enunciado. Investigar también el vectorizador tf-idf.

- **Clasificador**: investigar otros clasificadores mas efectivos que naive bayes. Estos deben poder retornar la probabilidad de pertenecia de las clases (ie: implementar la función `predict_proba`).

- **Features**: Recuerden que pueden implementar todas las features que se les ocurra! Aquí les adjuntamos algunos ejemplos:
    -	Word n-grams.
    -	Character n-grams. 
    -	Part-of-speech tags.
    -	Sentiment Lexicons (Lexicon = A set of words with a label or associated value.).
        - Count the number of positive and negative words within a sentence.
        - If the lexicon has associated intensity of feeling (for example in a decimal), then take the average of the intensity of the sentence according to the feeling, the sum, etc.
        -	A good lexicon of sentiment: [Bing Liu](http://www.cs.uic.edu/~liub/FBS/opinion-lexicon-English.rar) 
        - A reference with a lot of [sentiment lexicons](https://medium.com/@datamonsters/sentiment-analysis-tools-overview-part-1-positive-and-negative-words-databases-ae35431a470c). 
    -	The number of elongated words (words with one character repeated more than two times).
    -	The number of words with all characters in uppercase.
    -	The presence and the number of positive or negative emoticons.
    -	The number of individual negations.
    -	The number of contiguous sequences of dots, question marks and exclamation marks.
    -	Word Embeddings: Here are some good ideas on how to use them.
    https://stats.stackexchange.com/questions/221715/apply-word-embeddings-to-entire-document-to-get-a-feature-vector

- **Reducción de dimensionalidad**: También puede serles de ayuda. Referencias [aquí](https://scikit-learn.org/stable/modules/unsupervised_reduction.html).

- Por último, pueden encontrar mas referencias de cómo mejorar sus features, el vectorizador y el clasificador [aquí](https://affectivetweets.cms.waikato.ac.nz/benchmark/).

----------------------------------------

# 0. TODO
- Encontrar un bonito clasificador para las features.
- Modificar la funcion run para considerar las nuevos datasets balanceados.
- Experimentar.

## 1. Introducción

## 2. Representaciones

Para las representaciones se escogio...

## 3. Algoritmos

De los algoritmos de clasificación se decidió...

## 4. Métricas de Evaluación

- AUC: ...
- Kappa: El coeficiente kappa de Cohen es una métrica que establece qué tan certero es el clasificador con los resultados esperados teniendo en cuenta la posibilidad de que las predicciones acertadas pudieron haber sido por mero azar.

- Accuracy: El Accuracy mide la proporción de aciertos del clasificador de forma simple, contando la cantidad de clases bien predichas versus la cantidad de predicciones realizadas.


## 5. Experimentos

### Importar librerías y utiles

In [61]:
# Set-up
try:
    import emojis
except:
    !pip install emojis
    import emojis

try:
    import gensim.downloader as api
except:
    !pip install gensim

# !pip install -U imbalanced-learn

In [62]:
import pandas as pd
import os
import numpy as np
import shutil

import emojis
import gensim.downloader as api # https://github.com/RaRe-Technologies/gensim-data
# get the model
model = api.load("glove-twitter-25")


from nltk.tokenize import TweetTokenizer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.metrics import confusion_matrix, cohen_kappa_score, classification_report, accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier



### Definir métodos de evaluación

Estas funciones están a cargo de evaluar los resultados de la tarea. No deberían cambiarlas.


In [63]:
def auc_score(test_set, predicted_set):
    high_predicted = np.array([prediction[2] for prediction in predicted_set])
    medium_predicted = np.array(
        [prediction[1] for prediction in predicted_set])
    low_predicted = np.array([prediction[0] for prediction in predicted_set])
    high_test = np.where(test_set == 'high', 1.0, 0.0)
    medium_test = np.where(test_set == 'medium', 1.0, 0.0)
    low_test = np.where(test_set == 'low', 1.0, 0.0)
    auc_high = roc_auc_score(high_test, high_predicted)
    auc_med = roc_auc_score(medium_test, medium_predicted)
    auc_low = roc_auc_score(low_test, low_predicted)
    auc_w = (low_test.sum() * auc_low + medium_test.sum() * auc_med +
             high_test.sum() * auc_high) / (
                 low_test.sum() + medium_test.sum() + high_test.sum())
    return auc_w


def evaulate(predicted_probabilities, y_test, labels, dataset_name):
    # Importante: al transformar los arreglos de probabilidad a clases,
    # entregar el arreglo de clases aprendido por el clasificador.
    # (que comunmente, es distinto a ['low', 'medium', 'high'])
    predicted_labels = [
        labels[np.argmax(item)] for item in predicted_probabilities
    ]
    print('Confusion Matrix for {}:\n'.format(dataset_name))
    print(
        confusion_matrix(y_test,
                         predicted_labels,
                         labels=['low', 'medium', 'high']))

    print('\nClassification Report:\n')
    print(
        classification_report(y_test,
                              predicted_labels,
                              labels=['low', 'medium', 'high']))
    # Reorder predicted probabilities array.
    labels = labels.tolist()
    predicted_probabilities = predicted_probabilities[:, [
        labels.index('low'),
        labels.index('medium'),
        labels.index('high')
    ]]
    auc = round(auc_score(y_test, predicted_probabilities), 3)
    print("Scores:\n\nAUC: ", auc, end='\t')
    kappa = round(cohen_kappa_score(y_test, predicted_labels), 3)
    print("Kappa:", kappa, end='\t')
    accuracy = round(accuracy_score(y_test, predicted_labels), 3)
    print("Accuracy:", accuracy)
    print('------------------------------------------------------\n')
    return np.array([auc, kappa, accuracy])

### Datos ####

In [64]:

# Datasets de entrenamiento.
train = {
    'anger': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/anger-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity']),
    'fear': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/fear-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity']),
    'joy': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/joy-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity']),
    'sadness': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/sadness-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'])
}
# Datasets que deberán predecir para la competencia.
target = {
    'anger': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/anger-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE']),
    'fear': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/fear-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE']),
    'joy': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/joy-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE']),
    'sadness': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/sadness-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE'])
}

### Analizar los datos 

Imprimir la cantidad de tweets de cada dataset, según su intensidad de sentimiento. Noten que las clases están desbalanceadas. 

In [65]:
def get_group_dist(group_name, train):
    print(group_name, "\n",
          train[group_name].groupby('sentiment_intensity').count(),
          '\n---------------------------------------\n')
for dataset_name in train:
    get_group_dist(dataset_name, train)

anger 
                       id  tweet  class
sentiment_intensity                   
high                 163    163    163
low                  161    161    161
medium               617    617    617 
---------------------------------------

fear 
                       id  tweet  class
sentiment_intensity                   
high                 270    270    270
low                  288    288    288
medium               699    699    699 
---------------------------------------

joy 
                       id  tweet  class
sentiment_intensity                   
high                 195    195    195
low                  219    219    219
medium               488    488    488 
---------------------------------------

sadness 
                       id  tweet  class
sentiment_intensity                   
high                 197    197    197
low                  210    210    210
medium               453    453    453 
---------------------------------------



### Balance de Clases

In [66]:
from sklearn.utils import resample

#### Clasificador de Enojo ####

In [67]:
enojo=train.get('anger')
df_enojo_high=enojo['sentiment_intensity']=='high'
df_enojo_high=enojo[df_enojo_high]
df_enojo_medium=enojo['sentiment_intensity']=='medium'
df_enojo_medium=enojo[df_enojo_medium]
df_enojo_low=enojo['sentiment_intensity']=='low'
df_enojo_low=enojo[df_enojo_low]

In [68]:
# Downsample de medium
df_majority_downsampled = resample(df_enojo_medium, 
                                 replace=False,    # sample without replacement
                                 n_samples=163,     # to match minority class
                                 random_state=123) # reproducible results
 
# Se combinan las clases minoritarias con la mayoritaria
df_downsampled_enojo = pd.concat([df_majority_downsampled, df_enojo_low,df_enojo_high])
 
# Display new class counts
df_downsampled_enojo.sentiment_intensity.value_counts()

high      163
medium    163
low       161
Name: sentiment_intensity, dtype: int64

#### Clasificador de Miedo ####

In [69]:
miedo=train.get('fear')
df_miedo_high=miedo['sentiment_intensity']=='high'
df_miedo_high=miedo[df_miedo_high]
df_miedo_medium=miedo['sentiment_intensity']=='medium'
df_miedo_medium=miedo[df_miedo_medium]
df_miedo_low=miedo['sentiment_intensity']=='low'
df_miedo_low=miedo[df_miedo_low]

In [70]:
# Downsample de medium
df_majority_downsampled = resample(df_miedo_medium, 
                                 replace=False,    # sample without replacement
                                 n_samples=270,     # to match minority class
                                 random_state=123) # reproducible results
 
# Se combinan las clases minoritarias con la mayoritaria
df_downsampled_miedo = pd.concat([df_majority_downsampled, df_miedo_low,df_miedo_high])
 
# Display new class counts
df_downsampled_miedo.sentiment_intensity.value_counts()

low       288
high      270
medium    270
Name: sentiment_intensity, dtype: int64

#### Clasificador de Alegria ####

In [71]:
alegria=train.get('joy')
df_alegria_high=alegria['sentiment_intensity']=='high'
df_alegria_high=alegria[df_alegria_high]
df_alegria_medium=alegria['sentiment_intensity']=='medium'
df_alegria_medium=alegria[df_alegria_medium]
df_alegria_low=alegria['sentiment_intensity']=='low'
df_alegria_low=alegria[df_alegria_low]

In [72]:
# Downsample de medium
df_majority_downsampled = resample(df_alegria_medium, 
                                 replace=False,    # sample without replacement
                                 n_samples=200,     # to match minority class
                                 random_state=123) # reproducible results
 
# Se combinan las clases minoritarias con la mayoritaria
df_downsampled_alegria = pd.concat([df_majority_downsampled, df_alegria_low,df_alegria_high])
 
# Display new class counts
df_downsampled_alegria.sentiment_intensity.value_counts()

low       219
medium    200
high      195
Name: sentiment_intensity, dtype: int64

#### Clasificador de Tristeza ####

In [73]:
tristeza=train.get('sadness')
df_tristeza_high=tristeza['sentiment_intensity']=='high'
df_tristeza_high=tristeza[df_tristeza_high]
df_tristeza_medium=tristeza['sentiment_intensity']=='medium'
df_tristeza_medium=tristeza[df_tristeza_medium]
df_tristeza_low=tristeza['sentiment_intensity']=='low'
df_tristeza_low=tristeza[df_tristeza_low]

In [74]:
# Downsample de medium
df_majority_downsampled = resample(df_tristeza_medium, 
                                 replace=False,    # sample without replacement
                                 n_samples=200,     # to match minority class
                                 random_state=123) # reproducible results
 
# Se combinan las clases minoritarias con la mayoritaria
df_downsampled_tristeza = pd.concat([df_majority_downsampled, df_tristeza_low,df_tristeza_high])
 
# Display new class counts
df_downsampled_tristeza.sentiment_intensity.value_counts()

low       210
medium    200
high      197
Name: sentiment_intensity, dtype: int64

#### Features y Estimadores

In [75]:
# Feature de ejemplo
# https://scikit-learn.org/stable/data_transforms.html
class CharsCountTransformer(BaseEstimator, TransformerMixin):
    def get_relevant_chars(self, tweet):
        num_hashtags = tweet.count('#')       #
        num_exclamations = tweet.count('!')   #
        num_interrogations = tweet.count('?') #
        num_dots = tweet.count('.')           #
        num_emojis = emojis.count(tweet)      #
        return [num_hashtags, num_exclamations, num_interrogations, num_emojis, num_dots]

    def transform(self, X, y=None):
        chars = []
        for tweet in X:
            chars.append(self.get_relevant_chars(tweet))

        return np.array(chars)

    def fit(self, X, y=None):
        return self

class WordEmbeddingsTransformer(BaseEstimator, TransformerMixin):
    # Usa el diccionario y encuentra su origen
    def __init__(self, model):
      self.model = model

    def transform(self, X, y=None):
        aggregation = np.mean
        tokenizer = TweetTokenizer()
        doc_embeddings = []
        for tweet in X:
            tokens = tokenizer.tokenize(tweet)
            selected_words = []
            for token in tokens:
                if token in model.vocab:
                    selected_words.append(model[token])
            
            if len(selected_words) > 0:
                doc_emb = aggregation(np.array(selected_words), axis = 0)
                doc_embeddings.append(doc_emb)
            else:
                doc_embeddings.append(np.zeros(model.vector_size))

        return np.array(doc_embeddings)


    def fit(self, X, y=None):
        return self

# Template para una feature
class SentimentLexicon(BaseEstimator, TransformerMixin):
    def fun(self, tweet):
        # do something...
        return [0]

    def transform(self, X, y=None):
        a_list = []
        for tweet in X:
            a_list.append(tweet)
        return a_list

    def fit(self, X, y=None):
        return self


# Estimator
estimator = OneVsRestClassifier(LogisticRegression(max_iter=1000000))
# estimator = LogisticRegression(max_iter=1000000)
        

#### Pipeline ####

In [76]:
def sad_pipeline():
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer()),
                                    ('chars_count', CharsCountTransformer()),
                                    ('word_embeddings', WordEmbeddingsTransformer(model))
                                    ])), ('clf', estimator)])

def angry_pipeline():
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer()),
                                    ('chars_count', CharsCountTransformer()),
                                    ('word_embeddings', WordEmbeddingsTransformer(model))
                                    ])), ('clf', estimator)])
    
def fear_pipeline():
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer()),
                                    ('chars_count', CharsCountTransformer()),
                                    ('word_embeddings', WordEmbeddingsTransformer(model))
                                    ])), ('clf', estimator)])

def joy_pipeline():
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer()),
                                    ('chars_count', CharsCountTransformer()),
                                    ('word_embeddings', WordEmbeddingsTransformer(model))
                                    ])), ('clf', estimator)])

In [77]:
# Ejecutar el pipeline para algun data-set
def run(dataset, dataset_name, pipeline):
    """Creamos el pipeline y luego lo ejecutamos el pipeline sobre un dataset. 
    Retorna el modelo ya entrenado mas sus labels asociadas y los scores obtenidos al evaluarlo."""

    # Dividimos el dataset en train y test.
    X_train, X_test, y_train, y_test = train_test_split(
        dataset.tweet,
        dataset.sentiment_intensity,
        shuffle=True,
        test_size=0.33)

    # Entrenamos el clasificador (Ejecuta el entrenamiento sobre todo el pipeline)
    pipeline.fit(X_train, y_train)

    # Predecimos las probabilidades de intensidad de cada elemento del set de prueba.
    predicted_probabilities = pipeline.predict_proba(X_test)

    # Obtenemos el orden de las clases aprendidas.
    learned_labels = pipeline.classes_

    # Evaluamos:
    scores = evaulate(predicted_probabilities, y_test, learned_labels, dataset_name)
    return pipeline, learned_labels, scores
    

In [78]:
# Experiments
enojo_clasif, enojo_learned_labels, enojo_score = run(df_downsampled_enojo, 'anger', angry_pipeline())
miedo_clasif, miedo_learned_labels, miedo_score = run(df_downsampled_miedo, 'fear', fear_pipeline())
alegria_clasif, alegria_learned_labels, alegria_score = run(df_downsampled_alegria, 'joy', joy_pipeline())
tristeza_clasif, tristeza_learned_labels, tristeza_score = run(df_downsampled_tristeza, 'sadness', sad_pipeline())
    
# Get clasif/labels/scores
classifiers = [enojo_clasif, miedo_clasif, alegria_clasif, tristeza_clasif]
learned_labels_array = [enojo_learned_labels, miedo_learned_labels, alegria_learned_labels, tristeza_learned_labels]
scores_array = [enojo_score, miedo_score, alegria_score, tristeza_score]

# print avg scores
print(
    "Average scores:\n\n",
    "Average AUC: {0:.3g}\t Average Kappa: {1:.3g}\t Average Accuracy: {2:.3g}"
    .format(*np.array(scores_array).mean(axis=0)))


Confusion Matrix for anger:

[[29 21  9]
 [21 20 15]
 [ 1 12 33]]

Classification Report:

              precision    recall  f1-score   support

         low       0.57      0.49      0.53        59
      medium       0.38      0.36      0.37        56
        high       0.58      0.72      0.64        46

    accuracy                           0.51       161
   macro avg       0.51      0.52      0.51       161
weighted avg       0.51      0.51      0.50       161

Scores:

AUC:  0.695	Kappa: 0.266	Accuracy: 0.509
------------------------------------------------------

Confusion Matrix for fear:

[[48 31 12]
 [24 41 24]
 [13 22 59]]

Classification Report:

              precision    recall  f1-score   support

         low       0.56      0.53      0.55        91
      medium       0.44      0.46      0.45        89
        high       0.62      0.63      0.62        94

    accuracy                           0.54       274
   macro avg       0.54      0.54      0.54       274
weight

### Predecir los target set y crear la submission

Aquí predecimos los target set usando los clasificadores creados y creamos los archivos de las submissions.

In [79]:
def predict_target(dataset, classifier, labels):
    # Predecir las probabilidades de intensidad de cada elemento del target set.
    predicted = pd.DataFrame(classifier.predict_proba(dataset.tweet), columns=labels)
    # Agregar ids
    predicted['id'] = dataset.id.values
    # Reordenar las columnas
    predicted = predicted[['id', 'low', 'medium', 'high']]
    return predicted

In [80]:
predicted_target = {}

# Crear carpeta ./predictions
if (not os.path.exists('./predictions')):
    os.mkdir('./predictions')

else:
    # Eliminar predicciones anteriores:
    shutil.rmtree('./predictions')
    os.mkdir('./predictions')

# por cada target set:
for idx, key in enumerate(target):
    # Predecirlo
    predicted_target[key] = predict_target(target[key], classifiers[idx],
                                           learned_labels_array[idx])
    # Guardar predicciones en archivos separados. 
    predicted_target[key].to_csv('./predictions/{}-pred.txt'.format(key),
                                 sep='\t',
                                 header=False,
                                 index=False)

# Crear archivo zip
a = shutil.make_archive('predictions', 'zip', './predictions')

ValueError: X has 1772 features per sample; expecting 2305

## 6. Conclusiones

...